version: '3.8'

networks:
  docker-network:  # Nome da rede é docker-network

volumes:
  api_db_data:     # Volume para os dados do banco de dados
  node_modules:    # Volume para a pasta node_modules

services:
  api:
    container_name: nest_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app  # Volume para o código da aplicação
      - node_modules:/usr/src/app/node_modules  # Volume específico para node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    networks:
      - docker-network  # Associar à rede "docker-network"
    depends_on:
      - postgres

  postgres:
    container_name: nest_db
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data  # o nome da variável de ambiente é "PGDATA"
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    volumes:
      - api_db_data:/var/lib/postgresql/data
    networks:
      - docker-network  # Associar à rede "docker-network"
